#!/bin/sh

set -e

case "$1" in
    remove)
        # Use offline mode to configure service
        # firewalld will complain if potentially active service isn't removed before removing the definition
        firewall-offline-cmd --remove-service=revpi-modbus-default >/dev/null 2>&1 || true
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
